global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  # # Placeholder for other services
  # - job_name: 'nextcloud'
  #   static_configs:
  #     - targets: ['nextcloud:8080']

  # - job_name: 'database'
  #   static_configs:
  #     - targets: ['db:3306']
